token:
sendStatusMessage: true
newsGuildId:
newsChannelId:
newsChannelPublishWaitMilliSec: 1000
http.timeoutSec: 30
shardsTotal:
shardIds:
disableCommandUpdate: false
welcomeMessageStartTimePlusBufferSec: 300
shutdownWaitTimeSec: 10
db:
  url: jdbc:h2:file:./persistence/dice_config;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=5
  user:
  password:
metric:
  url: localhost
  port: 8080
diceEvaluator:
  maxNumberOfDice: 1000
  cacheSize: 10000
  maxNumberOfElements: 10000
  keepChildrenRolls: true
command:
  minDelayBetweenButtonMessagesMs: 1000
  delayMessageDataDeletionMs: 10000
  fetch.delayMs: 60000
  clear.messageDeleteDelay: 1000