token:
sendStatusMessage: true
newsGuildId:
newsChannelId:
newsChannelPublishWaitMilliSec: 1000
http:
  timeoutSec: 30
  thread.pool.size: 20
  logging: NONE
shardsTotal:
shardIds:
disableCommandUpdate: false
shutdownWaitTimeSec: 10
maxGuildCleanUpRatio: 0.1
# if it is a dev/beta instance, default is false
dev:
db:
  url: jdbc:h2:file:./persistence/dice_config;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=5
  user:
  password:
  deleteMarkMessageDataIntervalInMilliSec: 10000
  deleteMarkMessageDataStartDelayMilliSec: 0
  deleteMarkedConfigIntervalInMilliSec: 3600000 #1h
  deleteMarkedConfigStartDelayMilliSec: 0
  delayMessageDataDeletionMs: 10000
  delayMessageConfigDeletionMs: 604800000 #7 days
  delayChannelConfigDeletionMs: 604800000 #7 days
metric:
  url: localhost
  port: 8080
diceEvaluator:
  maxNumberOfDice: 1000
  cacheSize: 10000
  maxNumberOfElements: 10000
  keepChildrenRolls: false
  errorContextSize: 6
command:
  minDelayBetweenButtonMessagesMs: 1000
  fetch.delayMs: 60000
  clear.messageDeleteDelay: 1000