ALTER TABLE MESSAGE_CONFIG
    ADD COLUMN IF NOT EXISTS MARKED_DELETED TIMESTAMP;

CREATE INDEX IF NOT EXISTS MESSAGE_CONFIG_DELETE ON MESSAGE_CONFIG (MARKED_DELETED);
CREATE INDEX IF NOT EXISTS MESSAGE_CONFIG_GUILD_DELETE ON MESSAGE_CONFIG (GUILD_ID, MARKED_DELETED);

ALTER TABLE CHANNEL_CONFIG
    ADD COLUMN IF NOT EXISTS MARKED_DELETED TIMESTAMP;

CREATE INDEX IF NOT EXISTS CHANNEL_CONFIG_DELETE ON CHANNEL_CONFIG (MARKED_DELETED);
CREATE INDEX IF NOT EXISTS CHANNEL_CONFIG_GUILD_DELETE ON CHANNEL_CONFIG (GUILD_ID, MARKED_DELETED);
CREATE INDEX IF NOT EXISTS MESSAGE_DATA_GUILD_DELETE ON MESSAGE_DATA (GUILD_ID, MARKED_DELETED);
