ALTER TABLE MESSAGE_CONFIG
    ADD COLUMN IF NOT EXISTS CONFIG_NAME VARCHAR;
ALTER TABLE CHANNEL_CONFIG
    ADD COLUMN IF NOT EXISTS CONFIG_NAME VARCHAR;
ALTER TABLE CHANNEL_CONFIG
    ADD COLUMN IF NOT EXISTS CREATION_USER_ID BIGINT;
ALTER TABLE MESSAGE_CONFIG
    ADD COLUMN IF NOT EXISTS CREATION_USER_ID BIGINT;

CREATE INDEX IF NOT EXISTS MESSAGE_CONFIG_CD_UID_GID_N ON MESSAGE_CONFIG (CREATION_DATE, CREATION_USER_ID, GUILD_ID, CONFIG_NAME);
CREATE INDEX IF NOT EXISTS MESSAGE_CONFIG_CD_UID_GID_N_ID_CID ON MESSAGE_CONFIG (CREATION_DATE, CREATION_USER_ID,
                                                                                 GUILD_ID, CONFIG_NAME, COMMAND_ID,
                                                                                 CONFIG_ID);